# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='model.proto',
  package='tx',
  serialized_pb='\n\x0bmodel.proto\x12\x02tx\"l\n\x07\x43ontrol\x12\x0e\n\x06low_ep\x18\x01 \x02(\x05\x12\x0f\n\x07high_ep\x18\x02 \x02(\x05\x12\x0f\n\x07low_ep2\x18\x03 \x02(\x05\x12\x10\n\x08high_ep2\x18\x04 \x02(\x05\x12\r\n\x05\x63urve\x18\x05 \x03(\x05\x12\x0e\n\x06source\x18\x06 \x02(\x05\"\'\n\x07\x43hannel\x12\x0b\n\x03mix\x18\x01 \x03(\x05\x12\x0f\n\x07reverse\x18\x02 \x02(\x05\"D\n\x04Mode\x12\x1d\n\x08\x63ontrols\x18\x01 \x03(\x0b\x32\x0b.tx.Control\x12\x1d\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\x0b.tx.Channel\"0\n\x05Model\x12\x0e\n\x06num_ch\x18\x01 \x02(\x05\x12\x17\n\x05modes\x18\x02 \x03(\x0b\x32\x08.tx.Mode')




_CONTROL = descriptor.Descriptor(
  name='Control',
  full_name='tx.Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='low_ep', full_name='tx.Control.low_ep', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='high_ep', full_name='tx.Control.high_ep', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='low_ep2', full_name='tx.Control.low_ep2', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='high_ep2', full_name='tx.Control.high_ep2', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='curve', full_name='tx.Control.curve', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source', full_name='tx.Control.source', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=127,
)


_CHANNEL = descriptor.Descriptor(
  name='Channel',
  full_name='tx.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mix', full_name='tx.Channel.mix', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reverse', full_name='tx.Channel.reverse', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=168,
)


_MODE = descriptor.Descriptor(
  name='Mode',
  full_name='tx.Mode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='controls', full_name='tx.Mode.controls', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='channels', full_name='tx.Mode.channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=170,
  serialized_end=238,
)


_MODEL = descriptor.Descriptor(
  name='Model',
  full_name='tx.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='num_ch', full_name='tx.Model.num_ch', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='modes', full_name='tx.Model.modes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=240,
  serialized_end=288,
)


_MODE.fields_by_name['controls'].message_type = _CONTROL
_MODE.fields_by_name['channels'].message_type = _CHANNEL
_MODEL.fields_by_name['modes'].message_type = _MODE

class Control(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROL
  
  # @@protoc_insertion_point(class_scope:tx.Control)

class Channel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHANNEL
  
  # @@protoc_insertion_point(class_scope:tx.Channel)

class Mode(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODE
  
  # @@protoc_insertion_point(class_scope:tx.Mode)

class Model(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODEL
  
  # @@protoc_insertion_point(class_scope:tx.Model)

# @@protoc_insertion_point(module_scope)
